BASE_TASK_CONFIG_PATH: habitat_extensions/config/zs_vlnce_task.yaml
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
TORCH_GPU_IDS: [0]
GPU_NUMBERS: 1
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/tensorboard_dirs/
CHECKPOINT_FOLDER: data/checkpoints/
EVAL_CKPT_PATH_DIR: data/checkpoints/
RESULTS_DIR: data/logs/eval_results/
VIDEO_DIR: data/logs/video/
KEYBOARD_CONTROL: 0

SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']

MAP:
  VISUALIZE: False
  PRINT_IMAGES: False
  REPVITSAM: 1

EVAL:
  USE_CKPT_CONFIG: False
  SAVE_RESULTS: True
  SPLIT: val_unseen
  MIN_CONSTRAINT_STEPS: 10
  MAX_CONSTRAINT_STEPS: 25
  SCORE_THRESHOLD: 0.5
  VALUE_THRESHOLD: 0.30
  DECISION_THRESHOLD: 0.4
  FMM_WAYPOINT_THRESHOLD: 2.0
  FMM_GOAL_THRESHOLD: 1.0
  CHANGE_THRESHOLD: -0.03